#! /bin/bash

if [[ $# -eq 1 ]]; then
  file=$1
  printf ">> file $file\n"
  ./cm ../test/$file
  [[ $? -ne 0 ]] && exit 1
  ./a.out
  exit 0
fi

for file in $(ls ../test); do
  if [[ $file == *.sy ]]; then
    printf "\n>> file $file\n"
    ./cm ../test/$file
    [[ $? -ne 0 ]] && continue
    ./a.out
  fi
done

echo "test finished!"
